apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  serviceAccount: ynov
  containers:
  - name: debug
    image: asinatra/arpscan:v1.0.3
    command: ["sleep"]
    args: ["5000"]
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
