apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 4Gi