apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  {{- if .Values.labels }}
  labels:
  {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
  
