apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: asinatra/mongodbapp:latest
    env:
      - name: DB_URL
        value: mongodb://root:vbjnmBanUF@mongodbsvc:27017
