apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    app.kubernetes.io/name: nginx-cm
    app.kubernetes.io/instance: nginx-asinatra
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: nginx.conf
            path: nginx.conf
