apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  externalIPs:
  - 192.168.49.2
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx-lb
    app.kubernetes.io/instance: nginx-asinatra
  type: LoadBalancer
