apiVersion: v1
kind: Service
metadata:
  name: hello-world-init
spec:
  externalIPs:
  - 192.168.49.2
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hello-world-init
  type: LoadBalancer